Bug-#418-fix-lesson-mock-data
Studio-Yandex-Practicum/lizaalert_frontend pull request #421
Opened 2023-10-23 13:58 UTC by lipnitskaite

## Связанная задача: [#418 Баг - урок не отображается при выборе в содержании](https://github.com/Studio-Yandex-Practicum/lizaalert_frontend/issues/418)

### [Чеклист](https://github.com/Studio-Yandex-Practicum/lizaalert_frontend/blob/master/docs/style-guide.md)

### Описание выполненной работы:

Решена проблема, что в моковых данных промис инициализировался только в первый раз, когда выбираешь урок в содержании, из-за чего выбор остальных уроков не работал.
Буду благодарна за любые рекомендации по улучшению моего решения!

2023-10-26 13:28 UTC, elaineir requested changes

2023-10-26 13:28 UTC, elaineir commented on src/api/core/abstract/base.api.ts
> +      });
В общем, здесь в модуле надо вернуть функцию, которая возвращает промис, затем во втором `then` этот промис вызывается:

```suggestion
      return mock()
        .then(
          (module: { readonly default: () => Promise<T> }) => module.default
        )
        .then((fn) => fn());
```

2023-10-26 13:28 UTC, elaineir commented on src/api/lessons/lessons.api.ts
> +      mock: () => renderLesson(),
Здесь все оставим, как было

2023-10-26 13:28 UTC, elaineir commented on src/api/lessons/mock/lesson.ts
> +export default renderLesson;
Здесь будем возвращать промис, можно сразу через `Promise.resolve`:

```TypeScript
export default Promise.resolve(() => {
  const [, chapterId, lessonId] =
    window.location.pathname.match(/[1-9]/g) ?? [];
  const chapter = lessons[chapterId] ?? lessons[1];

  return chapter[lessonId] ?? chapter[1];
});
```

Важно поправить все остальные моки, чтобы они возвращали функцию. Лучше вынести данные в костанту:

```TypeScript
const courses: CoursesModel = {
  count: 8,
  results: [],
}
```
и затем в конце файла вернуть промис:

```TypeScript
export default Promise.resolve(() => courses);
```

2023-10-27 13:48 UTC, lipnitskaite commented on src/api/lessons/mock/lesson.ts
> +export default renderLesson;
спасибо огромное за помощь!! мотаю на ус :)

2023-10-30 07:55 UTC, elaineir approved these changes

2023-10-30 08:00 UTC, merged