#397 отправить результаты теста для валидации
Studio-Yandex-Practicum/lizaalert_frontend pull request #424
Opened 2023-10-26 16:21 UTC by apant94

## Связанная задача: [Отправить результаты теста для валидации и отрисовка результатов (frontend)](https://github.com/Studio-Yandex-Practicum/lizaalert_frontend/issues/397)

### [Чеклист](https://github.com/Studio-Yandex-Practicum/lizaalert_frontend/blob/master/docs/style-guide.md)

### Описание выполненной работы:

- [ х ] Создать запрос на бэкэнд с передачей ответов пользователя на вопросы теста.

- [ ] Получить результат валидации (ок или не ок, % верных ответов?)

- [ ] Отобразить результаты теста (% верных отаветов и сообщение пользователю) и отрисовать кнопку "Пересдать", если такая возможность у пользователя еще осталась (или всегда будем отрисовывать?).

- [ ] Получить информацию о правильных и не правильных ответах пользователя (наверное вместе с результатами теста) и подсветить ответы зеленым/красным (галочка и крестик)

2023-10-30 11:18 UTC, aimenin requested changes
Обсудим на синке реализацию, не очень ее понимаю

2023-10-30 11:18 UTC, aimenin commented on src/api/lessons/lessons.api.ts
> +  // TestOnValidationData,
нужен комментарий?

2023-10-30 11:18 UTC, aimenin commented on src/api/lessons/lessons.api.ts
> +      // mock: () => import('./mock/test'),
если будем оставлять в коде, то давай заведем issue, где опишим на каких условиях мы это возвращаем

2023-10-30 11:18 UTC, aimenin commented on src/components/organisms/test/hooks/use-test.ts
> +    // await dispatch(validateTest(2, answers));
здесь так же с комментарием - если оставляем заводим issue для него

2023-10-30 11:18 UTC, aimenin commented on src/store/test/slice.js
> +        ].filter((id) => id !== null),
зачем здесь фильтрация? Почему у нас может быть id - null?

2023-10-30 11:18 UTC, aimenin commented on src/store/test/thunk.ts
> +    console.log(answersData);
console.log- забыт в коде

2023-11-21 08:39 UTC, apant94 commented on src/api/lessons/lessons.api.ts
> +  // TestOnValidationData,
нет, удалила

2023-11-21 08:40 UTC, apant94 commented on src/components/organisms/test/hooks/use-test.ts
> +    // await dispatch(validateTest(2, answers));
удалила

2023-11-21 09:42 UTC, apant94 commented on src/store/test/thunk.ts
> +    console.log(answersData);
убрала

2023-11-21 09:43 UTC, apant94 commented on src/store/test/slice.js
> +        ].filter((id) => id !== null),
не помню, почему я так сделала, убрала так как и без этого все работает

2023-11-23 15:13 UTC, aimenin approved these changes
😎

2023-11-24 07:43 UTC, elaineir requested changes
ПР пока сырой, отправляю на доработку.

1) Типизировать test slice и selectors #294 
2) Поправить нейминг и типы
3) Замокать ответы бекенда
4) Исправить конфликты

2023-11-24 07:43 UTC, elaineir commented on src/api/lessons/lessons.api.ts
> +        privateApi.post(`${SERVICE_URL}${data.id}/quiz/run/`, data.answersData),
Исправить нейминги для метода и типов и добавить мок.

Называем функции по тому, что они делают, чтобы другим разработчикам сразу было понятно без погружения в контекст.
Из `postTest` понятно только, что это post-запрос. Что именно он делает -- не понятно.
Если он запускает валидацию теста, то так и нужно назвать: `validateTest`

По типам:
`Model` в проекте -- это то, что возвращает бекенд. Если что-то отправляется с фронта, то добавляем `Data`:
`(data: AnswersValidationData)`

А возвращаем модель. И модель приходит другая:
![Снимок экрана от 2023-11-24 11-02-05](https://github.com/Studio-Yandex-Practicum/lizaalert_frontend/assets/75016726/025be709-a1df-4133-95f2-c8bfb84ffb2a)

Только почему-то бекенд не присылает результат.

2023-11-24 07:43 UTC, elaineir commented on src/api/lessons/types.ts
> +  answersData: TestOnValidationData[];
Лучше просто `answers`

2023-11-24 07:43 UTC, elaineir commented on src/api/lessons/types.ts
> +export type AnswersOnValidationModel = {
```suggestion
export type AnswersValidationData = {
```

2023-11-24 07:43 UTC, elaineir commented on src/components/organisms/test/hooks/use-test.ts
> +  const { lessonId }: { lessonId?: number } = useParams();
Нет, параметры это всегда строки, и по умолчанию он типизирует верно.

```suggestion
  const { lessonId } = useParams();
```

2023-11-24 07:43 UTC, elaineir commented on src/store/test/selectors.js
>  export const selectIsTestLoading = (state) => state.test.isLoading;
В описании к задаче написано, что файл типизирован, но на самом деле нет

2023-11-24 07:43 UTC, elaineir commented on src/store/test/slice.js
Файл **необходимо** типизировать. По всем компонентам теста ошибки типизации, и дальше будет хуже, если сейчас с этим не разобраться.

2023-11-24 07:43 UTC, elaineir commented on src/store/test/thunk.ts
> +);
Тип уже определен в `api/lessons`, деструктурировать нет необходимости

```suggestion
export const validateTest = createAsyncThunk('test/validate', async (data: AnswersValidationData) => {
    const test = await lessonsApi.postTest(data);
    return test;
  });
```

2024-01-29 08:52 UTC, aimenin reviewed
Парочка вопросов

2024-01-29 08:52 UTC, aimenin commented on src/api/lessons/lessons.api.ts
> +      // mock: () => import('./mock/test'),
верни, пожалуйста моки в этот запрос

2024-01-29 08:52 UTC, aimenin commented on src/api/lessons/lessons.api.ts
> +      request: () =>
@elaineir 
Моки на такую функциональность делаем?

2024-01-29 08:52 UTC, aimenin commented on src/components/organisms/test/hooks/use-test.ts
> +  const testResult = useAppSelector(selectTestResult);
давай useAppSelector к остальным селекторам

2024-01-29 08:52 UTC, aimenin commented on src/components/organisms/test/hooks/use-test.ts
> +      setIsSuccess(percent >= 50);
50 в константы

2024-01-29 08:52 UTC, aimenin commented on src/store/test/slice.ts
> +    builder.addCase(validateTest.fulfilled, (state, { payload }) => {
на validateTest я бы тоже добавил обработчики на успех и ошибку

2024-01-29 08:52 UTC, aimenin commented on src/utils/calculate-percent.ts
> +export const calculatePercent = (
на синке нужно спросить, почему это не делается на беке

2024-01-30 15:42 UTC, elaineir requested changes
Начнем все заново 👾

2024-01-30 15:42 UTC, elaineir commented on src/components/organisms/test/hooks/use-test.ts
> +import { AVERAGE_TEST_RESULT } from 'utils/constants';
Порядок импортов, эти 12 и 13 надо подвинуть на 3 и 4

2024-01-30 15:42 UTC, elaineir commented on src/store/test/slice.ts
> +import { Controls, GENERAL_ERROR } from '../../utils/constants';
```suggestion
import { Controls, GENERAL_ERROR } from 'utils/constants';
```

2024-01-30 15:42 UTC, elaineir commented on src/store/test/slice.ts
> +}
Это в `./types.ts` и интерфейсы в проекте используем только для классов (class ... implements Interface).

type UpdateAnswerAction = {...}

2024-01-30 15:42 UTC, elaineir commented on src/store/test/thunk.ts
> +export const createTest = createAsyncThunk(
Санка не обрабатывается в сторе. Что будет, если запрос упадет или зависнет? Приложение не поймет, в каком статусе висит запрос и не сможет его обработать.

Если тело ответа не важно, то лучше не возвращать результат, оставить `await lessonsApi.createTest(id);`

2024-01-30 15:42 UTC, elaineir commented on src/store/test/types.ts
> +  isLoading: boolean;
Сейчас уходим от `isLoading`, для отслеживания статусов запроса используем поле `process: ProcesEnum`. Если критично различать запросы, то делаем несколько полей: `processValidate`, `processCreate` и т.д. Если не критично, то в одном.
Но тут видится, что будет лучше разделить, т.к. запросов много, и они последовательные. Если один упадет, то нарушится цепочка, и тест нельзя будет пройти.
Когда добавим тостеры, то можно будет хотя бы показать ошибку.

`isLoading` можно определить в селекторах.

Нужно обработать статусы в редьюсерах, как пример можно взять `lesson`

2024-01-30 15:42 UTC, elaineir commented on src/store/types.ts
> +import { TestState } from './test/types';
```suggestion
import type { TestState } from './test/types';
```

2024-01-30 15:42 UTC, elaineir commented on src/store/test/thunk.ts
> +import { AnswersValidationData } from 'api/lessons/types';
```suggestion
import type { AnswersValidationData } from 'api/lessons/types';
```

2024-01-30 16:00 UTC, elaineir commented
Еще момент. Проект не следует Conventional Commits, исторически сложилось писать комиты в следующем формате:

> В начале названия комита пишет номер задачи который он решает: со знака # для Github issue ИЛИ MIL- TM- (в зависимости от префикса команды) для задач из Linear и короткого описания на английском языке в kebab-case:
> Github: #21-create-button-component,
> Linear: MIL-1-create-button-component или TM-1-create-button-component

2024-02-01 05:13 UTC, alheym commented on src/api/lessons/types.ts
> +  answers: TestOnValidationData[];
запрос уходит на ${SERVICE_URL}${data.id}/quiz/answer/

2024-02-01 05:37 UTC, alheym commented on src/components/molecules/test-answer/types.ts
> +  isChecked?: boolean;
тип определен не мной, пока убрала
логику по подсветке ответов на синке решили перенести в другую таску

2024-02-01 06:49 UTC, alheym commented on src/store/test/thunk.ts
> +export const createTest = createAsyncThunk(
добавила обработчик запроса, пока просто отключаю кнопку на Показать результат у теста, чтобы не отправлять запрос
в дальнейшем, нужно будет более осознанно обрабатывать ошибку и в принципе не продвигать пользователя по цепочке рендеров, 
так же вопрос к бэку, почему при ошибке на сознание теста запрос на отправку результатов теста завершается без ошибки, должна быть реализована обработка этого сценария

2024-02-02 09:21 UTC, elaineir requested changes
Последняя небольшая доработка и вливаю :)

2024-02-02 09:21 UTC, elaineir commented on src/components/organisms/test/hooks/use-test.ts
> +  const isTestCreated = useAppSelector(selectProcessCreationTest);
В `isTestCreated` лежит не булева, а ProcessEnum, именование не очень подходит:

```suggestion
  const testCreationProcess = useAppSelector(selectProcessCreationTest);
```

Либо сразу сравнить, чтобы была булева:
```tsx
const isTestCreated = useAppSelector(selectProcessCreationTest) === ProcessEnum.Failed;
```

2024-02-02 09:21 UTC, elaineir commented on src/components/organisms/test/hooks/use-test.ts
> +    isTestCreated === 'Failed' ||
```suggestion
    isTestCreated === ProcessEnum.Failed ||
```

или сразу булеву поставить, если определить ее выше:

```suggestion
    isTestCreated ||
```

2024-02-04 11:42 UTC, aimenin approved these changes
👍

2024-02-04 11:42 UTC, aimenin commented on src/components/organisms/test/hooks/use-test.ts
> +    !test.questions?.some((question) =>
здесь, как я понимаю, у нас становится активна кнопка при выборе хотя бы одного ответа на вопросы.
Я бы пока оставил так, но потом на синке обсудил эту функциональность.

2024-02-04 12:11 UTC, alheym commented on src/components/organisms/test/hooks/use-test.ts
> +    !test.questions?.some((question) =>
да, это проверка для Показать результат, в принципе можно добавить условие, что ответ на вопрос в любом случае должен быть, но думаю с точки зрения user friendly лучше будет добавить проверку перед отправкой на сервер т.е. включать кнопку если выбран хотя бы один вариант ответа на один из вопросов, дать пользователю возможность на нее нажать, а потом подсветить тот вопрос, ответ на который не был дан вообще, и только после полного заполнения теста - отправлять результат
но так как в макетах это не отражено, пока оставила в таком виде

2024-02-04 12:29 UTC, aimenin commented on src/components/organisms/test/hooks/use-test.ts
> +    !test.questions?.some((question) =>
Да, хорошая идея. Мне нравится. Думаю, можно сделать issue в беклог на эту тему

2024-02-05 12:00 UTC, elaineir approved these changes

2024-02-05 12:02 UTC, merged