Enhancement-#415-Video-Lesson
Studio-Yandex-Practicum/lizaalert_frontend pull request #434
Opened 2023-11-10 22:24 UTC by lipnitskaite

## Связанная задача: [#415 Отобразить видеоурок](https://github.com/Studio-Yandex-Practicum/lizaalert_frontend/issues/415)

### [Чеклист](https://github.com/Studio-Yandex-Practicum/lizaalert_frontend/blob/master/docs/style-guide.md)

### Описание выполненной работы:
В VideoLesson в src передается video_link, также поле video_link добавлено в модель урока и моковые данные

2023-11-14 11:13 UTC, elaineir requested changes

2023-11-14 11:13 UTC, elaineir commented on src/pages/lesson/lesson.tsx
> +                {lessonType === 'Videolesson' && lesson.video_link !== null && (
```suggestion
                {lessonType === 'Videolesson' && lesson.video_link && (
```

Если придет пустая строка, то мы тоже ничего не покажем

2023-11-14 11:13 UTC, elaineir commented on src/api/lessons/mock/lesson.ts
> +        'https://www.youtube.com/embed/OFntCmDmuQQ?si=2eja4V-lyh56wynW',
Есть 99% вероятность, что контент-менеджер будет не в курсе embed-ссылок. Если он вставит в админке обычную ссылку на youtube, то плеер ничего не отобразит.

Надо уточнить, бекенд как-то валидирует этот момент или нет.

Как вариант, мы можем извлекать id видео и формировать правильную embed-ссылку.
Можно взять эту библиотеку: https://github.com/jmorrell/get-youtube-id

2023-11-15 10:22 UTC, aimenin reviewed
Обсудим с беком вставку ссылки

2023-11-15 10:22 UTC, aimenin commented on src/api/lessons/mock/lesson.ts
> +        'https://www.youtube.com/embed/OFntCmDmuQQ?si=2eja4V-lyh56wynW',
Согласен, лучше полагаться на себя в этом случае.
Нужно обсудить с бекендом сегодня на планировании

2023-11-15 10:22 UTC, aimenin commented on src/pages/lesson/lesson.tsx
> +                {lessonType === 'Videolesson' && lesson.video_link !== null && (
для типа урока у нас нет enum или составного объекта константы?

2023-11-17 13:27 UTC, lipnitskaite commented on src/pages/lesson/lesson.tsx
> +                {lessonType === 'Videolesson' && lesson.video_link !== null && (
не уверена, что верно поняла вопрос, у нас есть тип LessonType:

api -> course -> types.ts -> LessonType
`export type LessonType = 'Quiz' | 'Videolesson' | 'Webinar' | 'Lesson';`

2023-11-20 12:18 UTC, lipnitskaite commented
@aimenin @elaineir Реализовала добавление видео с помощью библиотеки get-youtube-id, теперь можно вставлять обычные youtube-ссылки. 
Также добавила компонент описания под видео, как договорились на созвоне в пятницу.

2023-11-20 14:48 UTC, aimenin approved these changes
😎

2023-11-20 14:48 UTC, aimenin commented on src/components/organisms/video-lesson/video-lesson.tsx
> +      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
насколько я понимаю при autoplay видео запустится сразу при загрузке страницы.
Я не очень люблю такое поведение, обсудим на синке как это лучше сделать

2023-11-20 14:50 UTC, aimenin commented on src/pages/lesson/lesson.tsx
> +                {lessonType === 'Videolesson' && lesson.video_link !== null && (
Да, я про это.
Я предпочитаю в таком случае пользоваться enum, что при сравнении не писать просто строку, а обращаться к полю enum

2023-11-21 11:30 UTC, lipnitskaite commented
@aimenin @aimenin привет! Убрала autoplay и отрефакторила lessonType с использованием enum

2023-11-21 15:05 UTC, elaineir commented on src/pages/lesson/lesson.tsx
> +                {lessonType === 'Videolesson' && lesson.video_link !== null && (
Прежняя команда выбрала union'ы вместо enum, чтобы не плодить объекты и не таскать их по файлам в импортах

2023-11-21 15:20 UTC, lipnitskaite commented on src/pages/lesson/lesson.tsx
> +                {lessonType === 'Videolesson' && lesson.video_link !== null && (
если что, то откатить изменения не проблема, я зато попрактиковалась с enum:)

2023-11-21 15:22 UTC, elaineir commented on src/pages/lesson/lesson.tsx
> +                {lessonType === 'Videolesson' && lesson.video_link !== null && (
Да не, просто комментирую, почему сейчас сделано в виде юнионов

2023-11-21 15:46 UTC, elaineir requested changes

2023-11-21 15:46 UTC, elaineir commented on package.json
> +    "get-youtube-id": "^1.0.1",
```suggestion
    "get-youtube-id": "1.0.1",
```

Зависимости фиксируем. Нужно будет ещё раз выполнить `npm i`, чтобы обновился package-lock.json

2023-11-21 15:46 UTC, elaineir commented on src/components/organisms/video-lesson/video-lesson.module.scss
> +}
Давай сделаем это классом для динамического Markdown:

```css
.markdown {
  margin-top: 32px;
}
```

Отступ будет только в том случае, если Markdown отрендерился на странице

2023-11-21 15:46 UTC, elaineir commented on src/components/organisms/video-lesson/video-lesson.tsx
> +    <Markdown>{description ?? ''}</Markdown>
Не вставляем маркдаун, если нет `description`:

```tsx
{description && <Markdown>{description}</Markdown>}
```

Без этого условия на странице рендерится пустой `div`

2023-11-21 15:46 UTC, elaineir commented on src/pages/lesson/lesson.tsx
> +import { LessonType } from 'api/course';
Это на 21 строку перед `import { UserLessonProgress } from 'api/lessons'`, к константам

2023-11-21 15:46 UTC, elaineir commented on src/pages/lesson/lesson.tsx
> +  const isLesson = lesson.lesson_type === LessonType.Lesson;
Верни, пожалуйста, селектор `const lessonType = useAppSelector(selectLessonType)`, а здесь обращайся к нему, чтобы четыре раза не ходить в объект к одному и тому же свойству:

```tsx
const isQuiz = lessonType === LessonType.Quiz;
```

2023-11-21 15:46 UTC, elaineir commented on src/api/course/types.ts
> +export enum LessonType {
Нужно ещё забежать в `src/store/lesson/slice.ts` и пофиксить значение для `lesson_type`

2023-11-24 06:38 UTC, elaineir approved these changes

2023-11-24 06:39 UTC, merged