#444-validation-profile
Studio-Yandex-Practicum/lizaalert_frontend pull request #449
Opened 2023-11-25 18:03 UTC by MariaGrom

### [Чеклист](https://github.com/Studio-Yandex-Practicum/lizaalert_frontend/blob/master/docs/style-guide.md)

### Описание выполненной работы:

В профиле пользователя изменена валидация на формик,
в схему валидации добавлены правила по дате рождения, региону, никнейму и аватару, 
заблокирована возможность изменять почту в профиле

2023-11-27 10:16 UTC, aimenin reviewed
Никогда не работал с формиком, для меня все выглядит отлично.
Но я бы подождал ревью человека, знакомого с библиотекой, возможно можно как нибудь улучшить

2023-11-27 10:16 UTC, aimenin commented on src/utils/validation.ts
> +  name: string()
А откуда в итоге эти правила были взяты?
Где то в брифе зафиксированы?

2023-11-27 10:16 UTC, aimenin commented on src/components/organisms/personal-data/personal-data.tsx
> +    const data = {
а зачем здесь эта диструкторизация?

2023-11-27 14:45 UTC, MariaGrom commented on src/utils/validation.ts
> +  name: string()
данные к паролям тянутся с форм авторизации/регистрации. честно говоря, валидацию данных полей делала Алена, а я как-то и не спросила почему такие правила- уточню.

2023-12-03 08:02 UTC, elaineir requested changes

2023-12-06 14:53 UTC, elaineir requested changes

2023-12-09 09:53 UTC, MariaGrom commented
внесла изменения в форму "данные аккаунта" на основании последнего синка - убрала поле пароль, сделала номер телефона редактируемым полем, а также подправила текст справа от формы в соответствии с новыми правилами уникальности почты, вместо телефона.

2023-12-11 12:02 UTC, aimenin approved these changes
Мне нравится, оставил пару комментариев по улучшениям

2023-12-11 12:02 UTC, aimenin commented on src/components/organisms/account-data/account-data.tsx
> +    void formik.setValues(accountData);
при долгой загрузке у нас показываются пустые поля в профиле, которые потом меняются на заполенные?
Можно сделать issue на улучшение этого поведения и добавления загрузки

2023-12-11 12:02 UTC, aimenin commented on src/components/organisms/personal-data/personal-data.tsx
> +  'name',
строки выносим в константы, чтобы два раза не писать и не иметь возможности ошибиться

2023-12-11 12:15 UTC, elaineir requested changes

2023-12-11 12:15 UTC, elaineir commented on src/components/organisms/account-data/account-data.tsx
> +          disabled={areSameValues && (formik.isSubmitting || !formik.isValid)}
```suggestion
          disabled={areSameValues || formik.isSubmitting}
```
С `!formik.isValid` будут проблемы, лучше без него

2023-12-11 12:15 UTC, elaineir commented on src/components/organisms/personal-data/personal-data.tsx
> +          disabled={areSameValues && (formik.isSubmitting || !formik.isValid)}
```suggestion
          disabled={areSameValues || formik.isSubmitting}
```

2023-12-12 16:56 UTC, MariaGrom commented
Добавила данные о пользователе в константы в emun.
Изменила условия для блокировки кнопки "Сохранить" - вернула блокировку по валидации формика. 
без него кнопка не блокируется при явных ошибках в полях формы.
<img width="1067" alt="Снимок экрана 2023-12-12 в 20 50 36" src="https://github.com/Studio-Yandex-Practicum/lizaalert_frontend/assets/102763756/3359f559-2aa1-4dbf-b9c0-8502055c377c">

2023-12-15 08:51 UTC, elaineir requested changes

2023-12-15 08:51 UTC, elaineir commented on src/components/organisms/personal-data/personal-data.tsx
> +  console.log('formik.isValid', formik.isValid);
Все логи убираем

2023-12-15 08:51 UTC, elaineir commented on src/utils/constants.ts
> +  phone = 'phone',
В енамах ключи принято писать с заглавной буквы
https://www.typescriptlang.org/docs/handbook/enums.html

Name = 'name',
и т.д.

2023-12-15 08:51 UTC, elaineir commented on src/components/organisms/account-data/account-data.tsx
> +const fieldsToCompare = ['phone'];
Если вводим енам с названиями полей для формы, то тогда нужно его везде использовать, чтобы минимизировать ошибки:

```suggestion
const initialValues: AccountFormData = {
  [UserDataFieldNames.Email]: '',
  [UserDataFieldNames.Phone]: '',
};

const fieldsToCompare = [UserDataFieldNames.Phone];
```

2023-12-15 08:51 UTC, elaineir commented on src/components/organisms/account-data/account-data.tsx
> +          value={formik.values.phone}
```suggestion
          name={UserDataFieldNames.Phone}
          value={formik.values[UserDataFieldNames.Phone]}
```

2023-12-15 08:51 UTC, elaineir commented on src/components/organisms/account-data/account-data.tsx
> +          value={formik.values.email}
```tsx
name={UserDataFieldNames.Email}
value={formik.values[UserDataFieldNames.Email]}
```

В другой форме аналогично

2023-12-15 08:51 UTC, elaineir commented on src/components/organisms/account-data/types.ts
>    email: string;
```tsx
[UserDataFieldNames.Phone]: string;
/** Email пользователя. */
[UserDataFieldNames.Email]: string;
```

2023-12-15 08:51 UTC, elaineir commented on src/utils/validation.ts
Ну и в этом файле тогда нужно названия полей привязать к енаму

2023-12-15 08:51 UTC, elaineir commented on src/components/organisms/account-data/account-data.tsx
> +          disabled={areSameValues || !formik.isValid}
Куда делся `formik.isSubmitting`?
Он блокирует кнопку на время запроса

2023-12-15 08:51 UTC, elaineir commented on src/components/organisms/personal-data/personal-data.tsx
> +          disabled={areSameValues || !formik.isValid}
+ `formik.isSubmitting`

По поводу `!formik.isValid` уже писала, что будут проблемы.
Когда пользак только зарегистрировался, у него везде будут null в полях, кроме телефона и почты.
С этой настройкой он начнет менять одно поле в форме и увидит, что кнопка всё ещё заблокирована.
Его естественная реакция будет: WTF?
При изменении любого поля нужно включать кнопку, чтобы он видел, что форма отзывчивая.
Поэтому надо либо писать костылики, либо не выключать кнопку, если форма при сабмите содержит ошибки. Запрос при ошибках все равно не отправится

2023-12-15 08:51 UTC, elaineir commented on src/utils/validation.ts
> +    .required(messages.required),
Корректная дата не проходит

![Снимок экрана от 2023-12-15 12-22-21](https://github.com/Studio-Yandex-Practicum/lizaalert_frontend/assets/75016726/d278041c-188a-45c1-aa6b-36a11e183037)

2023-12-19 11:35 UTC, elaineir approved these changes

2023-12-19 11:37 UTC, merged