Development 457 achievements in profile
Studio-Yandex-Practicum/lizaalert_frontend pull request #480
Opened 2024-01-18 11:17 UTC by Natali-Vorobeva

## Связанная задача: [Добавить отображение ачивок в профиль пользователя](https://github.com/Studio-Yandex-Practicum/lizaalert_frontend/issues/457)

### Описание выполненной работы:
Создан компонент (Achievements) с ачивками и tooltip, в котором при наведении на ачивку появляется tooltip с информацией об этой ачивке. 
Для реализации созданы два компонента Achievement и Tooltip.

Появилась и сохраняется ошибка, которую победить пока не получается (
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of InputMaskChildrenWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference.)

2024-01-19 11:37 UTC, elaineir requested changes

2024-01-19 11:37 UTC, elaineir commented on src/components/organisms/account-overview/account-overview.tsx
> +import { useDispatch } from 'react-redux';
Импорты из библиотек идут первыми. Этот импорт нужно перенести на 2 строку

2024-01-19 11:37 UTC, elaineir commented on src/components/organisms/account-overview/account-overview.tsx
> +    void dispatch(fetchAchievement() as any);
Не типизируем через any

2024-01-19 11:37 UTC, elaineir commented on src/components/organisms/account-overview/types.ts
> +export type AchievementsType = AchievementType[];
Дубли апи моделей, удаляем

2024-01-19 11:37 UTC, elaineir commented on src/components/molecules/tooltip/tooltip.module.scss
> +    &Text {
```suggestion
      }
      
      &Text {
        margin: 5px;
      }
    }
    
    &Text {
```
Селекторы разделяем пустой строкой

2024-01-19 11:37 UTC, elaineir commented on src/components/molecules/achievement/index.ts
> +export { Achievement } from './achievement';
```suggestion
export { Achievement } from './achievement';
export type { AchievementProps } from './types';
```

Пропы тоже экспортируем

2024-01-19 11:37 UTC, elaineir commented on src/components/organisms/achievements/achievements.module.scss
> +.achievements {
1) Контейнер не выдерживает переполнение контентом:

![Снимок экрана от 2024-01-19 14-58-35](https://github.com/Studio-Yandex-Practicum/lizaalert_frontend/assets/75016726/8b04a348-9946-4552-8b5e-dcae3e717baa)

Нужно или переносить на вторую и последующие строки, либо показывать определенное количество.

2) Селекторы разделяем пустой строкой

2024-01-19 11:37 UTC, elaineir commented on src/components/organisms/achievements/achievements.tsx
> +        <div className={styles.achievementsFlex}>
Для чего используется два флекс-контейнера и пустой див между ними?

Все ачивки можно отрендерить в одном флекс-контейнере `<div className={styles.achievements}>`

2024-01-19 11:37 UTC, elaineir commented on src/components/organisms/achievements/achievements.tsx
> +  const dataAchievements = useAppSelector(selectAchievements);
```suggestion
  const achievements = useAppSelector(selectAchievements);
```

Если при запросе случится ошибка или ачивок не будет, то на странице отрендерится пустой див (сейчас даже три). Нужно добавить проверку на длину массива и возвращать из компонента `null`, если массив пустой.

2024-01-19 11:37 UTC, elaineir commented on src/components/organisms/achievements/index.ts
В этом файле нужно экспортировать компонент и тип его пропов

2024-01-19 11:37 UTC, elaineir commented on src/components/organisms/achievements/types.ts
> +export type AchievementsProps = object;
Здесь нужно добавить проп `className`

2024-01-19 11:38 UTC, elaineir commented
Ещё обрати, пожалуйста, внимание на то, как оформлять коммиты:
https://github.com/Studio-Yandex-Practicum/lizaalert_frontend?tab=readme-ov-file#работа-с-git

> в начале названия комита пишет номер задачи который он решает: со знака # для Github issue ИЛИ MIL- TR- (в зависимости от префикса команды) для задач из Linear и короткого описания на английском языке в kebab-case

2024-01-19 15:14 UTC, Di0niz commented
TM-13

2024-01-22 15:27 UTC, aimenin requested changes
Поправить замечания Алены

2024-01-22 15:27 UTC, aimenin commented on src/api/achievements/mock/achievements.ts
> +  // {
не думаю, что комментарии здесь нужны, если что раскопируем снова

2024-01-22 15:27 UTC, aimenin commented on src/components/molecules/achievement/achievement.tsx
> +    <>
чтобы не делать такую обертку можно чуть переделать Tooltip
Я бы передавал туда контент, по наведению на которой открывается tooltip, в качестве children.
Таким образом нам не придется постоянно делать обертку <></>

2024-01-22 15:27 UTC, aimenin commented on src/components/molecules/tooltip/index.ts
Пустой файл не оставляем, как я понял это index, здесь реэспортируем остальные файлы

2024-01-22 15:27 UTC, aimenin commented on src/components/organisms/achievements/achievements.module.scss
> +.achievements {
Насколько понял, переполнение исправлено

2024-02-04 12:28 UTC, aimenin reviewed
Пока не мержим, некоторые комментарии не поправлены.
Плюс обсудим по эндпойнту

2024-02-04 12:28 UTC, aimenin commented on src/components/molecules/achievement/index.ts
> +export { Achievement } from './achievement';
Насколько я вижу, комментарий не исправлен.

2024-02-04 12:28 UTC, aimenin commented on src/components/molecules/tooltip/tooltip.module.scss
> +  @media (max-width: 961px) {
961?
У нас есть константы для брейкпоинтов в проекте?

2024-02-04 12:28 UTC, aimenin commented on src/api/achievements/achievements.api.ts
> +const SERVICE_URL = '/profile/';
Странно, что ачивки получаем по profile, потому что ачивки работают не только на profile

В issue про profile уже сделаны api для получаения данных profile, на синке нужно решить, оставляем ачивки на эндпойнте profile или нет

2024-02-04 12:28 UTC, aimenin commented on src/components/molecules/tooltip/types.ts
> +export type TooltipProps = {
Conversation резолвится либо с комментарием, если что то решили в личном общении, либо если оно исправлено.
Здесь какой случай?

2024-02-09 09:14 UTC, Artem-Mit commented on src/api/achievements/achievements.api.ts
> +const SERVICE_URL = '/profile/';
На синке решили, что оставляем /profile/

2024-02-09 09:15 UTC, Artem-Mit commented on src/components/molecules/tooltip/tooltip.module.scss
> +  @media (max-width: 961px) {
Удалил медиазапрос, т.к. он бесполезный.)

2024-02-09 11:03 UTC, elaineir commented on src/components/molecules/tooltip/types.ts
> +export type TooltipProps = {
Комментарий не актуален, к сожалению, текущая верстка компонента не предполагает его переиспользование вне Achievements

2024-02-11 13:24 UTC, aimenin approved these changes
😎

2024-02-12 13:17 UTC, elaineir requested changes
Поправить конфликты и ещё пару комментариев

2024-02-12 13:17 UTC, elaineir commented on src/api/achievements/index.ts
> +export type { AchievementsModel } from './types';
Здесь ещё нужно реэкспортнуть `achievementApi`

2024-02-12 13:17 UTC, elaineir commented on src/components/molecules/tooltip/tooltip.module.scss
> +    border: 5px solid colors.$dark-primary;
Свойство повторяется на 25 строке

2024-02-12 13:17 UTC, elaineir commented on src/store/achievements/thunk.ts
> +import { achievementApi } from 'api/achievements/achievements.api';
```suggestion
import { achievementApi } from 'api/achievements';
```

2024-02-18 09:59 UTC, elaineir approved these changes

2024-02-18 09:59 UTC, merged