#57-fixed-display-of-lessons
Studio-Yandex-Practicum/lizaalert_frontend pull request #495
Opened 2024-01-30 14:51 UTC by ZzZorger

## Связанная задача: [MIL-57](https://linear.app/lizaalert/issue/MIL-57/privesti-v-poryadok-soderzhanie-na-stranicah-uroka-i-kursa)

### [Стайлгайд](https://github.com/Studio-Yandex-Practicum/lizaalert_frontend/blob/master/docs/style-guide.md)

### Описание выполненной работы:

_В компоненте обрабатывающем отрисовку уроков поменял переменную в условии в соответствии с данными с бэка, также поменял значения списка констант переменной LessonProgress со строковых на числовые для правильного выполнения условий_

2024-01-30 16:11 UTC, elaineir requested changes
По коду замечаний нет, но нужна небольшая доработка: в файле `src/api/course/mock/course.ts` в массиве `chapters` обновить поля `lesson_progress` на `user_lesson_progress`, чтобы все работало и на моках

2024-01-31 10:02 UTC, ZzZorger commented
Изменил названия переменной в моках

2024-01-31 13:54 UTC, aimenin reviewed
Данный pr закрывает полную задачу MIL-57, или остались какие то не сделанные пункты?

2024-01-31 15:23 UTC, ZzZorger commented
> Данный pr закрывает полную задачу MIL-57, или остались какие то не сделанные пункты?

Да, закрывает полностью:

- пройденный уроки отображаются зеленой галочкой; 

- активный урок отображается оранжевым цветом; 

- при наведении на пройденный урок, он отображается оранжевым цветом; 

- на пройденный и активный уроки можно переходить кликом.

2024-02-01 12:33 UTC, merged