TM-32: Отобразить профиль пользователя
Studio-Yandex-Practicum/lizaalert_frontend pull request #496
Opened 2024-01-31 16:53 UTC by shinonhorror

## Связанная задача: [Отобразить профиль пользователя](https://linear.app/lizaalert/issue/TM-32/otobrazit-profil-polzovatelya)

### [Стайлгайд](https://github.com/Studio-Yandex-Practicum/lizaalert_frontend/blob/master/docs/style-guide.md)

### Описание выполненной работы:

- [x] Отображение данных пользователя
  - [x] Имя
  - [x] Фото
  - [x] Город
  - [x] Номер
  - [ ] Ник
- [x] Редактирование данных пользователя (ожидание бэка):
  - [x] Имя
  - [x] Фото
  - [ ] Город
  - [ ] Номер
  - [ ] Ник
- [x] Добавлен метод pluralize для корректного отображения окончаний (в данном случае - кол-во пройденных курсов)

2024-02-02 10:12 UTC, elaineir requested changes

2024-02-02 10:12 UTC, elaineir commented on src/api/profile/mock/profile.ts
> +  photo: '../../../assets/images/profile-mock.jpg',
```suggestion
import profileMockImage from 'assets/images/profile-mock.jpg';
import type { ProfileModel } from '../types';

const profile: ProfileModel = {
  id: 0,
  photo: profileMockImage,
```

Без предварительного импорта картинка не отобразится + id поменять на число

2024-02-02 10:12 UTC, elaineir commented on src/api/mock/profile.json
>  {
Теперь мок приходит через апи, этот файл можно удалить

2024-02-02 10:12 UTC, elaineir commented on src/components/organisms/personal-data/personal-data.tsx
> +// TODO: после добавления nickname в модель раскомментировать код
Надо завести задачу на бэк и фронт в линеаре и допом вставить сюда ссылку на фронтовую задачу, иначе забудем

2024-02-04 11:53 UTC, aimenin approved these changes
Парочка комментариев, в остальном не вижу проблем

2024-02-04 11:53 UTC, aimenin commented on src/store/profile/types.ts
> +      full_name: string | null;
если не ошибаюсь в проекте есть тип Nullable, который является удобной обвязкой для таких типов
```ts
Nullable<string>
```

2024-02-04 11:53 UTC, aimenin commented on src/utils/pluralize.ts
> +export function pluralize(value: number, words: string[]) {
не очень понимаю, что делает эта функция

Методы Intl не помогут в решении данной задачи?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules

2024-02-05 07:25 UTC, shinonhorror commented on src/utils/pluralize.ts
> +export function pluralize(value: number, words: string[]) {
Для методов Intl все равно нужно  будет писать функцию-обертку, так что в принципе выходит одинаково

2024-02-05 12:13 UTC, elaineir reviewed
Нужно пофиксить конфликт

2024-02-05 12:13 UTC, elaineir commented on src/store/profile/thunk.ts
> +    return {
А зачем убрана mapper-функция? С ней было удобнее + меньше править в будущем, если какое-то из полей поменяется.

Комментарий про объект в прошлом ревью был про возвращаемый объект из функции, без создания промежуточной переменной

2024-02-05 13:02 UTC, shinonhorror commented on src/store/profile/thunk.ts
> +    return {
А, окей, я видимо не так поняла коммент

2024-02-05 13:16 UTC, shinonhorror commented on src/store/profile/types.ts
> +      full_name: string | null;
Этот тип возвращает также и undefined, а тут именно string | null

2024-02-05 13:25 UTC, elaineir approved these changes

2024-02-05 13:25 UTC, merged