TM-27: Отобразить результаты тестирования
Studio-Yandex-Practicum/lizaalert_frontend pull request #497
Opened 2024-02-04 09:22 UTC by alheym

## Связанная задача: [Отобразить результаты тестирования](https://linear.app/lizaalert/issue/TM-27/otobrazit-rezultaty-testirovaniya)

### [Стайлгайд](https://github.com/Studio-Yandex-Practicum/lizaalert_frontend/blob/master/docs/style-guide.md)

### Описание выполненной работы:

Отображение результатов тестирование:

- [x] отображение правильных вариантов
- [x] отображение неправильный вариантов
- [x] отображение правильных, но не выбранных вариантов

2024-02-04 12:37 UTC, aimenin requested changes
Пока что посмотрел код, как это выглядит еще не видел.
По коду парочка улучшений

2024-02-04 12:37 UTC, aimenin commented on src/components/molecules/test-results/test-results.tsx
> +  if (validateAnswers[answer.id] === 'correct') {
correct, incorrect и unanswered давай в enum

2024-02-04 12:37 UTC, aimenin commented on src/components/molecules/test-results/test-results.tsx
> +const CORRECT_SELECTED_ANSWER = 'checkSolid';
давай вынесем константы из компонента и соберем их в enum

2024-02-04 12:37 UTC, aimenin commented on src/utils/validateAnswers.ts
> +    const result: Record<number, 'correct' | 'unanswered' | 'incorrect'> = {};
Record<number, 'correct' | 'unanswered' | 'incorrect'> - используется два раза точно, давай сделаем тип для результата

2024-02-04 12:37 UTC, aimenin commented on src/utils/validateAnswers.ts
> +        result[answerId] = 'correct';
про correct, unanswered и тд уже писал

2024-02-05 13:18 UTC, elaineir requested changes
Дополнительно обновиться к мастер-ветке и поправить конфликты

2024-02-05 13:18 UTC, elaineir commented on src/components/organisms/test/test.module.scss
> +}
Для последнего ребенка (псевдокласс `:last-child`) нужно обнулить нижний `margin`, иначе появляется лишний отступ

2024-02-07 10:13 UTC, elaineir requested changes

2024-02-07 10:13 UTC, elaineir commented on src/components/molecules/test-results/types.ts
> +  validateAnswers: Record<number, 'correct' | 'unanswered' | 'incorrect'>;
Тут подойдет `ResultRecord` из `src/components/organisms/test/types.ts` в качестве типа, но тогда нарушится иерархия импортов между компонентами. Молекулы не могут импортировать файлы организмов.

Лучше перенести `ResultRecord` и `ResultStatus` в этот файл, а остальные будут импортировать их отсюда.

2024-02-07 11:28 UTC, aimenin requested changes
Отличная работа.
От меня парочка замечаний + поправить, то, что советует Алена

2024-02-07 11:28 UTC, aimenin commented on src/components/organisms/test/hooks/use-test.ts
> +import { TestValidateType } from '../types';
```suggestion
import type { TestValidateType } from '../types';
```

2024-02-07 11:28 UTC, aimenin commented on src/components/organisms/test/test.module.scss
> +  margin-bottom: 16px;
с помощью flex-gap в данном случае не получится разнести чекбоксы?
Может вкусовщина, но я margin вообще стараюсь не использовать

2024-02-07 11:28 UTC, aimenin commented on src/pages/lesson/lesson.tsx
> +    const isQuizType = lesson.lesson_type === 'Quiz';
Quiz - мне кажется у нас есть enum с перечислением типов урока

2024-02-18 13:37 UTC, elaineir commented on src/components/organisms/test/test.module.scss
> +  margin-bottom: 16px;
Разнесла через gap

2024-02-18 13:40 UTC, elaineir commented on src/pages/lesson/lesson.tsx
> +    const isQuizType = lesson.lesson_type === 'Quiz';
Ага, к тому же эта переменная уже определена в коде выше, но здесь задавалась заново...
Еще зачем-то через перерисовку всей страницы было сделано, когда можно точечно задизейблить кнопку.

2024-02-19 09:53 UTC, aimenin approved these changes
👍

2024-02-19 10:30 UTC, elaineir approved these changes

2024-02-19 10:31 UTC, merged