Feature/MIL-74
Studio-Yandex-Practicum/lizaalert_frontend pull request #503
Opened 2024-02-21 14:26 UTC by gineff

## Связанная задача: [Скомпоновать форму Домашнего задания](https://linear.app/lizaalert/issue/MIL-74/skomponovat-formy)

### [Стайлгайд](https://github.com/Studio-Yandex-Practicum/lizaalert_frontend/blob/master/docs/style-guide.md)

### Описание выполненной работы:

- добавлен компонент Textarea
- добавлен компонент Homework
- добавлено отображение Homerwork на странице Lesson
- добавен mock hook useHomework, который в MIL-75 переписан с использованием homework api и store

2024-02-22 13:42 UTC, elaineir requested changes

2024-02-22 13:42 UTC, elaineir commented on src/components/molecules/textarea/textarea.tsx
> +export const Textarea: FC<TextareaProps> = ({
Компонент немного не соответствует макету:
https://www.figma.com/file/FasUcYffR2kJAhPvBGcACW/LizaAlert-Mockups?type=design&node-id=122-2403&mode=design&t=0oCnYeNYUaew7x9F-4

placeholder использует цвет dark-secondary, в фокусе wrapper должен выделяться оранжевой обводкой, при ошибке подкрашиваться красным

2024-02-22 13:42 UTC, elaineir commented on src/components/organisms/homework/homework.module.scss
> +}
Уже есть в textarea

2024-02-22 13:42 UTC, elaineir commented on src/components/organisms/homework/homework.module.scss
> +}
Это свойство определить в самой textarea, чтобы у всех компонентов было одинаковое поведение

2024-02-22 13:42 UTC, elaineir commented on src/components/organisms/homework/homework.tsx
> +/* eslint-disable @typescript-eslint/no-unused-vars */
Здесь нет необходимости выключать линтер

2024-02-22 13:42 UTC, elaineir commented on src/components/organisms/homework/homework.tsx
> +import { useEffect, type FC, useState } from 'react';
useState не используется

2024-02-22 13:42 UTC, elaineir commented on src/components/organisms/homework/homework.tsx
> +  const textLengthLimit = 5000;
Константы выносим перед компонентом, чтобы они не создавались каждый раз при ререндере, а только 1 раз за сессию.
Комментарий к константе избыточен, кмк

2024-02-22 13:42 UTC, elaineir commented on src/components/organisms/homework/homework.tsx
> +  };
В `./types.ts`

2024-02-22 13:42 UTC, elaineir commented on src/components/organisms/homework/homework.tsx
> +            disabled={homework.status !== HomeworkStatus.Draft}
`homework.status !== HomeworkStatus.Draft` повторяется 3 раза, лучше вынести в переменную

2024-02-22 13:42 UTC, elaineir commented on src/components/organisms/homework/homework.tsx
> +  };
Это тоже можно вынести перед компонентом, как константу

2024-02-22 13:42 UTC, elaineir commented on src/components/organisms/homework/homework.module.scss
> +}
В кнопку передается несуществующий класс `submitButton`, а `button` не используется.
Если ограничивать размеры кнопки не надо, то оба класса следует удалить

2024-02-22 13:50 UTC, elaineir commented
Ещё чисто визуально не оч. красиво, когда можно сужать поле textarea по горизонтали, и в disabled-состоянии у нее серый фон появляется:

![Peek 2024-02-22 17-48](https://github.com/Studio-Yandex-Practicum/lizaalert_frontend/assets/75016726/85caf5c7-ea20-417a-ab40-d1c803bacd4e)

2024-02-25 16:23 UTC, aimenin approved these changes
От меня только пара небольших комментариев

2024-02-25 16:23 UTC, aimenin commented on src/components/organisms/homework/homework.tsx
> +  /** лимит по количеству знаков в ответе */
нужен комментарий?

2024-02-25 16:23 UTC, aimenin commented on src/components/organisms/homework/homework.tsx
> +const textLengthLimit = 5000;
я бы как минимум экспортировал эту константу, а лучше бы вынес ее из компонента

2024-02-27 14:24 UTC, elaineir approved these changes

2024-02-27 14:25 UTC, merged