TM-48: Интеграция с Я.Паспорт на стороне frontend
Studio-Yandex-Practicum/lizaalert_frontend pull request #505
Opened 2024-02-29 14:12 UTC by Artem-Mit

## Связанная задача: [Интеграция с Я.Паспорт на стороне frontend](https://linear.app/lizaalert/issue/TM-48/integraciya-s-yapasport-na-storone-frontend)

### [Стайлгайд](https://github.com/Studio-Yandex-Practicum/lizaalert_frontend/blob/master/docs/style-guide.md)

### Описание выполненной работы:
Добавлен метод в апи авторизации
Добавлен thunk
Переработан компонент кнопки авторизации через яндекс
Прошу проверить нейминг и типизацию, как будто бы можно было сделать красивее)

2024-03-01 12:46 UTC, elaineir requested changes

2024-03-01 12:46 UTC, elaineir commented on .env.example
> +YANDEX_REDIRECT_URI=http://localhost:3000/auth
С текущим CI/CD на проде `http://localhost:3000` работать не будет, у нас нет управления переменными окружения на разных контурах.

Редирект в любом случае будет происходить на `window.location.origin`, что можно прописать в `YandexOAuthButton`, а эту переменную удалить.
Или прописать сюда продовый урл, а в девелопменте менять на локалхост.

2024-03-01 12:46 UTC, elaineir commented on src/components/molecules/yandex-oauth-button/yandex-oauth-button.tsx
> +    window.location.href = `https://oauth.yandex.ru/authorize?response_type=token&client_id=${YANDEX_CLIENTID}&redirect_uri=${YANDEX_REDIRECT_URI}`;
1) Почему не через `assign`? https://developer.mozilla.org/en-US/docs/Web/API/Location/assign
Он секьюрный и для написания юнит-тестов больше подходит.

2) Эту строку лучше бы вынести над компонентом как константу, от пропов она не зависит.

2024-03-01 12:46 UTC, elaineir commented on src/api/authorization/index.ts
> +} from './types';
```suggestion
  OauthTokenData,
  AuthorizationModel,
} from './types';
```

Все, что используется вне модуля, реэкспортируем "наружу".
`index.ts` - это интерфейс модуля, при импорте дальше него проваливаться в файлы нежелательно

2024-03-01 12:46 UTC, elaineir commented on src/pages/auth/auth.tsx
> +import { extractOauthToken } from 'utils/extract-oauth-token';
```suggestion
import { type FC, useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { routes } from 'config';
import type { OauthTokenData, AuthorizationModel } from 'api/authorization';
import { extractOauthToken } from 'utils/extract-oauth-token';
import { useAppDispatch } from 'store';
import { loginByOauth } from 'store/auth/thunk';
```

Порядок импортов

2024-03-01 12:46 UTC, elaineir commented on src/pages/auth/auth.tsx
> +  });
Не по flux

1) Компонент подписан на стор, на токены с бэка и на ошибку
2) При монтировании компонент вызывает санку по получению токенов
3) Санка делает свое дело и кладет токены или ошибку в стор
4) При обновлении стора компонент перерисовывается и выполняет логику по редиректу или показу ошибки

В обход стора логику с апи не пишем.

2024-03-01 12:46 UTC, elaineir commented on src/pages/auth/index.ts
> +  () => import(/* webpackChunkName: "CoursesPage" */ './auth')
```suggestion
  () => import(/* webpackChunkName: "AuthPage" */ './auth')
```

2024-03-05 13:09 UTC, aimenin approved these changes
👍

2024-03-05 13:09 UTC, aimenin commented on .env.example
> +YANDEX_CLIENTID=b3be356844ef4136bb188934b323a609
А что за клиент здесь?

2024-03-05 13:35 UTC, Artem-Mit commented on .env.example
> +YANDEX_CLIENTID=b3be356844ef4136bb188934b323a609
Это айдишник тестовой учетки, которую я сделал. Его нужно будет заменить на ту учетку, через которую будет работать авторизация.

2024-03-05 14:07 UTC, elaineir approved these changes

2024-03-05 14:10 UTC, elaineir commented on .env.example
> +YANDEX_CLIENTID=b3be356844ef4136bb188934b323a609
@aimenin Будем что-то делать с секретами или сливаем как есть?

2024-03-05 14:42 UTC, elaineir commented on .env.example
> +YANDEX_CLIENTID=b3be356844ef4136bb188934b323a609
@Artem-Mit Если будешь сливать, обрати, пожалуйста внимание на:
1) Название комита, `TM-48-add-yandex-oauth (#505)`
2) Кнопка должна называться `Squash and merge`, можно выбрать, если нажать на стрелочку справа

![Без названия](https://github.com/Studio-Yandex-Practicum/lizaalert_frontend/assets/75016726/8b605282-136b-4492-82fe-7bc648ab63f4)

![Без названия](https://github.com/Studio-Yandex-Practicum/lizaalert_frontend/assets/75016726/9a6fdff8-449b-4fb2-b818-4fffbef21fc6)

2024-03-11 15:45 UTC, Artem-Mit commented on .env.example
> +YANDEX_CLIENTID=b3be356844ef4136bb188934b323a609
@elaineir @aimenin Изменил clientID на актуальный, все работает. Смержите?) Не знаю можно ли мерджить, столько времени прошло с последнего коммента...

2024-03-12 09:24 UTC, merged