MIL-99: Настроить отображение вебинаров
Studio-Yandex-Practicum/lizaalert_frontend pull request #506
Opened 2024-03-04 09:43 UTC by ZzZorger

## Связанная задача: [MIL-99: Настроить отображение вебинаров](https://linear.app/lizaalert/issue/MIL-99/nastroit-otobrazhenie-vebinarov)

### [Стайлгайд](https://github.com/Studio-Yandex-Practicum/lizaalert_frontend/blob/master/docs/style-guide.md)

### Описание выполненной работы:

- Добавлена сущность вебинара, взаимодействующая с ручкой **/lessons/{lesson_id}/webinar/**
- Добавлена логика отображения вебинара - если тип урока webinar, то происходит запрос по ручке с вебинаром

2024-03-04 11:47 UTC, ZzZorger commented
Добавил условный рендеринг в зависимости от статуса вебинара. Если статус 0 - то отрисовывается PreviewWebinar, если статус 0 - то отрисовывается VideoLesson

2024-03-04 15:20 UTC, aimenin requested changes
парочка замечаний

2024-03-04 15:20 UTC, aimenin commented on src/api/lessons/lessons.api.ts
> +      request: () => privateApi.get(`${SERVICE_URL}${id}/webinar`),
добавляем моки для вебинара

2024-03-04 15:20 UTC, aimenin commented on src/hooks/use-lesson.ts
> +    if (lesson.lesson_type === 'Webinar') {
Webinar у нас лежит в enum где то, ну или должен лежать, поэтому сравниваем с этим энамом

2024-03-04 15:20 UTC, aimenin commented on src/api/lessons/types.ts
> +  status?: number;
для статуса создаем enum

2024-03-04 17:02 UTC, ZzZorger commented on src/api/lessons/lessons.api.ts
> +      request: () => privateApi.get(`${SERVICE_URL}${id}/webinar`),
А данные есть для мока вебинара? Ссылки на видео или что-то подобное

2024-03-04 20:43 UTC, ZzZorger commented
- Добавил mock данные и enum для типа уроки и для статуса вебинара

2024-03-05 14:19 UTC, elaineir requested changes

2024-03-05 14:19 UTC, elaineir commented on src/api/lessons/types.ts
> +  Completed = 1,
```suggestion
  Planned,
  Completed ,
```

В енамах значения по умолчанию нумеруются с 0 с шагом 1

2024-03-05 14:19 UTC, elaineir commented on src/hooks/use-lesson.ts
> +import { LessonModel, WebinarModel, UserLessonProgress } from 'api/lessons';
```suggestion
import { LessonModel, LessonType, WebinarModel, UserLessonProgress } from 'api/lessons';
```

а 22 строку `import { LessonType } from '../api/lessons/types';` удалить

2024-03-05 14:19 UTC, elaineir commented on src/store/webinar/selectors.ts
> +/* eslint-disable @typescript-eslint/no-unsafe-member-access */
Здесь нет необходимости выключать правило

2024-03-05 15:22 UTC, ZzZorger commented on src/store/webinar/selectors.ts
> +/* eslint-disable @typescript-eslint/no-unsafe-member-access */
Да, забыл удалить

2024-03-05 15:40 UTC, ZzZorger commented
Добавил правки

2024-03-06 14:08 UTC, merged