MIL-75-add-homework-features
Studio-Yandex-Practicum/lizaalert_frontend pull request #509
Opened 2024-03-05 15:55 UTC by gineff

## Связанная задача: [Добавить переходы статусов](https://linear.app/lizaalert/issue/MIL-75/dobavit-perehody-statusov)

### [Стайлгайд](https://github.com/Studio-Yandex-Practicum/lizaalert_frontend/blob/master/docs/style-guide.md)

### Описание выполненной работы:

- Добавлено homework api
- Добавлено homework redux store
- Добавлен хук use-homework

2024-03-07 07:14 UTC, elaineir reviewed
+ в utils/constants.ts остался enum HomeworkStatus, его нужно удалить, раз он теперь в api

2024-03-07 07:14 UTC, elaineir commented on src/hooks/use-homework.tsx
>      return answer;
Здесь вопрос: зачем возвращать `answer`, если результат функции в компоненте `Homework` не важен?

Уменьшаем вложенность и избавляемся от тернарника:
```tsx
if (!answer) {
  return;
}

const isAnswerChanged = homework.text !== answer;

void dispatch(
  updateHomework({
    id: lessonId,
    answer: {
      ...homework,
      text: answer,
      ...(isAnswerChanged && { status: HomeworkStatus.Submitted }),
    },
  })
);
```

2024-03-07 07:14 UTC, elaineir commented on src/store/homework/selectors.ts
> +*/
Если закомментированный код не нужен, то удаляем, иначе его следует раскомментировать

2024-03-07 07:14 UTC, elaineir commented on src/store/homework/slice.ts
> +        }
Для группировки санок в тулките есть специальные утилки, и они всё типизируют как нужно:

```suggestion
        isFulfilled(fetchHomeworkByLessonId, updateHomework),
        (state, { payload }) => {
          state.homework = payload;
          state.process = ProcessEnum.Succeeded;
          state.error = null;
        }
```

2024-03-07 07:14 UTC, elaineir commented on src/store/homework/slice.ts
> +        }
```suggestion
        isPending(fetchHomeworkByLessonId, updateHomework),
        (state) => {
          state.process = ProcessEnum.Requested;
          state.error = null;
        }
```

2024-03-07 07:14 UTC, elaineir commented on src/store/homework/slice.ts
> +        }
```suggestion
        isRejected(fetchHomeworkByLessonId, updateHomework),
        (state, { error }) => {
          state.process = ProcessEnum.Failed;
          state.error = error;
        }
```

2024-03-07 07:14 UTC, elaineir commented on src/store/homework/types.ts
> +import { HomeworkModel } from 'api/homework';
```suggestion
import type { HomeworkModel } from 'api/homework';
```

2024-03-07 07:15 UTC, elaineir requested changes
Забыла поставить чекбокс. См. комменты выше

2024-03-07 11:34 UTC, gineff commented on src/api/homework/homework.api.ts
> +const SERVICE_URL = (lessonId: string) => `lessons/${lessonId}/homework`;
Такая конструкция потому что в GET запросе нет необходимости слеша в конце

2024-03-11 13:38 UTC, elaineir reviewed
Конфликты бы еще поправить

@aimenin Посмотри ПР, пожалуйста

2024-03-11 13:38 UTC, elaineir commented on src/store/homework/slice.ts
> +          state.homework = payload as HomeworkModel;
```suggestion
          state.homework = payload;
```

as не надо

2024-03-11 13:38 UTC, elaineir commented on src/store/homework/slice.ts
> +            state.error = error as SerializedError;
```suggestion
            state.error = error;
```

as не надо

2024-03-11 14:52 UTC, elaineir approved these changes

2024-03-12 10:41 UTC, aimenin approved these changes
👍

2024-03-12 13:05 UTC, merged